# Generated by Django 3.0.5 on 2020-04-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='change_percent',
            field=models.FloatField(default=0.0),
        ),
    ]
