# Generated by Django 3.0.5 on 2020-04-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_stock_change_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='updated',
            field=models.CharField(max_length=50),
        ),
    ]
