# Generated by Django 3.0.5 on 2020-05-04 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200503_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment', models.FloatField()),
                ('money_amount', models.FloatField()),
                ('stock_amount', models.IntegerField()),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Stock')),
            ],
        ),
    ]
