# Generated by Django 3.0.5 on 2020-05-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='buy_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
