# Generated by Django 3.0.5 on 2020-05-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200505_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
