# Generated by Django 3.0.6 on 2020-06-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_stock_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='owner',
            field=models.CharField(choices=[('CA', 'Caco'), ('RI', 'Ricardo'), ('IT', 'Itala'), ('TH', 'Thayssa')], default='CA', max_length=2),
        ),
    ]
