# Generated by Django 3.0.6 on 2020-06-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_wallet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.CharField(choices=[('Caco', 'Caco'), ('Ricardo', 'Ricardo'), ('Itala', 'Itala'), ('Thayssa', 'Thayssa')], default='Caco', max_length=7),
        ),
    ]
