# Generated by Django 3.0.6 on 2020-06-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200601_1713'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='name of constraint',
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('owner', 'stock'), name='Owner and Stock'),
        ),
    ]
