# Generated by Django 3.0.6 on 2020-06-01 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200601_1714'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wallet',
            name='Owner and Stock',
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('owner', 'stock')},
        ),
    ]
