# Generated by Django 3.0.6 on 2020-06-02 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200601_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Stock'),
        ),
    ]
