# Generated by Django 3.0.5 on 2020-06-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200601_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=50)),
                ('operation', models.CharField(choices=[('Compra', 'Compra'), ('Compra e Venda', 'Compra e Venda'), ('Venda', 'Venda')], max_length=25)),
                ('document', models.FileField(upload_to='', verbose_name='documents/pdfs')),
                ('date', models.DateField(verbose_name='Data da transação')),
                ('broker', models.CharField(choices=[('Agora - Caco', 'Agora - Caco'), ('Agora - Ricardo', 'Agora - Ricardo'), ('BB - Ricardo', 'BB - Ricardo'), ('BB - Itala', 'BB - Itala')], max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.CharField(choices=[('Caco', 'Caco'), ('Ricardo', 'Ricardo'), ('Itala', 'Itala'), ('Thayssa', 'Thayssa'), ('Itala-Caco', 'Itala-Caco')], default='Caco', max_length=11),
        ),
    ]
