# Generated by Django 3.0.5 on 2020-06-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200620_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='broker',
            field=models.CharField(choices=[('Agora - Caco', 'Agora - Caco'), ('BB - Ricardo', 'BB - Ricardo'), ('BB - Itala', 'BB - Itala'), ('BB - Thayssa', 'BB - Thayssa')], max_length=25),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='owner',
            field=models.CharField(choices=[('Caco', 'Caco'), ('Ricardo', 'Ricardo'), ('Itala', 'Itala'), ('Thayssa', 'Thayssa')], default='Caco', max_length=11),
        ),
    ]
